project_name: "rust_libs"
target: "x86_64-unknown-linux-gnu"

dependencies:
  serde: "1.0"
  tokio: "1.0"

build_config:
  profile: "release"
  features: []
  no_default_features: false
  
compilation:
  debug_info: true
  optimization_level: 2
  link_time_optimization: false
  
output:
  rlib_dir: "data/compiled/rlibs"
  objects_dir: "data/compiled/objects"
  signatures_dir: "data/signatures"